version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cadastro_postgres
    environment:
      POSTGRES_DB: cadastro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170195
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
